"""
Zero-shot classification prompt templates

OpenAI simple ImageNet templates adapted from OpenCLIP:
https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/zero_shot_metadata.py

OpenAI templates adapted from:
https://github.com/openai/CLIP/blob/main/data/prompts.md
"""

# Reference license: MIT

DEFAULT_TEMPLATES = ("a photo of a {}.",)

IDENTITY_TEMPLATES = ("{}",)

SIMPLE_IMAGENET_TEMPLATES = (
    "itap of a {}.",
    "a bad photo of the {}.",
    "a origami {}.",
    "a photo of the large {}.",
    "a {} in a video game.",
    "art of the {}.",
    "a photo of the small {}.",
)

OPENAI_IMAGENET_TEMPLATES = (
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "a photo of a {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of a {}.",
    "the plushie {}.",
    "a dark photo of a {}.",
    "itap of a {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}.",
)

OPENAI_CIFAR10_TEMPLATES = (
    "a photo of a {}.",
    "a blurry photo of a {}.",
    "a black and white photo of a {}.",
    "a low contrast photo of a {}.",
    "a high contrast photo of a {}.",
    "a bad photo of a {}.",
    "a good photo of a {}.",
    "a photo of a small {}.",
    "a photo of a big {}.",
    "a photo of the {}.",
    "a blurry photo of the {}.",
    "a black and white photo of the {}.",
    "a low contrast photo of the {}.",
    "a high contrast photo of the {}.",
    "a bad photo of the {}.",
    "a good photo of the {}.",
    "a photo of the small {}.",
    "a photo of the big {}.",
)

OPENAI_CALTECH101_TEMPLATES = (
    "a photo of a {}.",
    "a painting of a {}.",
    "a plastic {}.",
    "a sculpture of a {}.",
    "a sketch of a {}.",
    "a tattoo of a {}.",
    "a toy {}.",
    "a rendition of a {}.",
    "a embroidered {}.",
    "a cartoon {}.",
    "a {} in a video game.",
    "a plushie {}.",
    "a origami {}.",
    "art of a {}.",
    "graffiti of a {}.",
    "a drawing of a {}.",
    "a doodle of a {}.",
    "a photo of the {}.",
    "a painting of the {}.",
    "the plastic {}.",
    "a sculpture of the {}.",
    "a sketch of the {}.",
    "a tattoo of the {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "the embroidered {}.",
    "the cartoon {}.",
    "the {} in a video game.",
    "the plushie {}.",
    "the origami {}.",
    "art of the {}.",
    "graffiti of the {}.",
    "a drawing of the {}.",
    "a doodle of the {}.",
)

OPENAI_COUNTRY211_TEMPLATES = (
    "a photo i took in {}.",
    "a photo i took while visiting {}.",
    "a photo from my home country of {}.",
    "a photo from my visit to {}.",
    "a photo showing the country of {}.",
)

OPENAI_EUROSAT_TEMPLATES = (
    "a centered satellite photo of {}.",
    "a centered satellite photo of a {}.",
    "a centered satellite photo of the {}.",
)

OPENAI_FGVC_AIRCRAFT_TEMPLATES = (
    "a photo of a {}, a type of aircraft.",
    "a photo of the {}, a type of aircraft.",
)

OPENAI_KINETICS_TEMPLATES = (
    "a photo of {}.",
    "a photo of a person {}.",
    "a photo of a person using {}.",
    "a photo of a person doing {}.",
    "a photo of a person during {}.",
    "a photo of a person performing {}.",
    "a photo of a person practicing {}.",
    "a video of {}.",
    "a video of a person {}.",
    "a video of a person using {}.",
    "a video of a person doing {}.",
    "a video of a person during {}.",
    "a video of a person performing {}.",
    "a video of a person practicing {}.",
    "a example of {}.",
    "a example of a person {}.",
    "a example of a person using {}.",
    "a example of a person doing {}.",
    "a example of a person during {}.",
    "a example of a person performing {}.",
    "a example of a person practicing {}.",
    "a demonstration of {}.",
    "a demonstration of a person {}.",
    "a demonstration of a person using {}.",
    "a demonstration of a person doing {}.",
    "a demonstration of a person during {}.",
    "a demonstration of a person performing {}.",
    "a demonstration of a person practicing {}.",
)

TEMPLATE_SETS = {
    "default": DEFAULT_TEMPLATES,
    "identity": IDENTITY_TEMPLATES,
    "simple_imagenet": SIMPLE_IMAGENET_TEMPLATES,
    "openai_imagenet": OPENAI_IMAGENET_TEMPLATES,
    "openai_cifar10": OPENAI_CIFAR10_TEMPLATES,
    "openai_caltech101": OPENAI_CALTECH101_TEMPLATES,
    "openai_country211": OPENAI_COUNTRY211_TEMPLATES,
    "openai_eurosat": OPENAI_EUROSAT_TEMPLATES,
    "openai_fgvc_aircraft": OPENAI_FGVC_AIRCRAFT_TEMPLATES,
    "openai_kinetics": OPENAI_KINETICS_TEMPLATES,
}
